[package]
name = "rust-hello-world"
version = "0.1.0"
authors = ["Dan Fox <iamdanfox@gmail.com>"]

[dependencies]

[dependencies.iron]
version = "*"

[dependencies.bodyparser]
git = "https://github.com/iron/body-parser.git"
